### ISSUE TITLE
system sound issues 

### ISSUE THREAD

**Issue by saddamhh** [reiryuki/Miui-Screen-Recorder-Magisk-Module#2]
Mai coustom rom mei miui screen recoder magisk module install kiya hai...bt when i start record then speaker and headphones sound suani nehi deta
..how to fix this..pls help...pls

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations (I'm not Indian)
2) Magisk install log if it's a Magisk module
3) Full logcat
4) Zipped Z folder

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

**Comment by saddamhh** [comment]
when i start recording then speaker and headphones sound mute

**Comment by reiryuki** [comment]
it's known issue

**Comment by harryqt** [comment]
Any workaround or fix?
